image: docker:latest

variables:
  - HAPROXY_BRANCH: "devel"
  - HAPROXY_MAJOR: "3.1"
  - HAPROXY_VERSION: "3.1-dev0"

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - docker login -u "$HUB_USERNAME" -p "$HUB_PASSWORD" $HUB_REGISTRY
  - docker buildx create --name haproxy_builder
  - docker buildx use haproxy_builder

build-master:
  stage: build
  tags:
    - arm
  script:
    - docker buildx build \
                --shm-size=512m \
                --platform linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7 \
                --no-cache \
                --pull \
                --tag "$CI_REGISTRY_IMAGE:experimental" \
                --build-arg VCS_REF=$(git rev-parse --short HEAD) \
                --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
                --build-arg HAPROXY_BRANCH=$HAPROXY_BRANCH \
                --build-arg HAPROXY_MAJOR=$HAPROXY_MAJOR \
                --build-arg HAPROXY_VERSION=$HAPROXY_VERSION \
                --push \
                .
  only:
    - master

build:
  stage: build
  tags:
    - arm
  script:
    - |-
        CI_COMMIT_TAG=$CI_COMMIT_REF_NAME
        if [ "${CI_COMMIT_REF_NAME:0:1}" == "v" ]; then
          CI_COMMIT_TAG=${CI_COMMIT_REF_NAME:1};
          if [[ "$CI_COMMIT_REF_NAME" =~ ^v([0-9]+\.[0-9]+)(.*)$ ]]; then
            docker buildx build \
                --shm-size=512m \
                --platform linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7 \
                --no-cache \
                --pull \
                --tag "$CI_REGISTRY_IMAGE:${BASH_REMATCH[1]}" \
                --tag "joramk/haproxy:${BASH_REMATCH[1]}" \
                --tag "$CI_REGISTRY_IMAGE:${BASH_REMATCH[1]}${BASH_REMATCH[2]}" \
                --tag "joramk/haproxy:${BASH_REMATCH[1]}${BASH_REMATCH[2]}" \
                --tag "$CI_REGISTRY_IMAGE:devel" \
                --tag "joramk/haproxy:devel" \
                --tag "$CI_REGISTRY_IMAGE:dev" \
                --tag "joramk/haproxy:dev" \
                --build-arg VCS_REF=$(git rev-parse --short HEAD) \
                --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
                --build-arg HAPROXY_BRANCH=$HAPROXY_BRANCH \
                --build-arg HAPROXY_MAJOR=$HAPROXY_MAJOR \
                --build-arg HAPROXY_VERSION=$HAPROXY_VERSION \
                --push \
                .
          fi
        else
          docker buildx build \
                --shm-size=512m \
                --platform linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7 \
                --no-cache \
                --pull \
                --tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" \
                --build-arg VCS_REF=$(git rev-parse --short HEAD) \
                --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
                --build-arg HAPROXY_BRANCH=$HAPROXY_BRANCH \
                --build-arg HAPROXY_MAJOR=$HAPROXY_MAJOR \
                --build-arg HAPROXY_VERSION=$HAPROXY_VERSION \
                .
        fi
  except:
    - master

after_script:
  - docker buildx stop haproxy_builder
  - docker buildx rm haproxy_builder

