image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - docker login -u "$HUB_USERNAME" -p "$HUB_PASSWORD" $HUB_REGISTRY
  - docker buildx create --name haproxy_builder1
  - docker buildx use haproxy_builder1

build-master:
  stage: build
  tags:
    - arm
  script:
    - docker buildx build --shm-size=512m --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 --no-cache --pull -t "$CI_REGISTRY_IMAGE:latest" --push .
  only:
    - master

build:
  stage: build
  tags:
    - arm
  script:
    - CI_COMMIT_TAG=$CI_COMMIT_REF_NAME
    - if [ "${CI_COMMIT_REF_NAME:0:1}" == "v" ]; then
        CI_COMMIT_TAG=${CI_COMMIT_REF_NAME:1};
      fi
    - docker buildx build --shm-size=512m --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 --no-cache --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" --push .
    - if [ "${CI_COMMIT_REF_NAME:0:1}" == "v" ]; then
        docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" "joramk/haproxy:$CI_COMMIT_TAG";
        docker push "joramk/haproxy:${CI_COMMIT_REF_NAME:1}";
      fi
    - case "$CI_COMMIT_TAG" in *\.*\.*)
        CI_SHORT_TAG=`echo "$CI_COMMIT_TAG" | sed -e 's/\([0-9.]\.[0-9.]\).*/\1/'`;
        docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" "joramk/haproxy:$CI_SHORT_TAG";
        docker push "joramk/haproxy:$CI_SHORT_TAG";
        docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" "joramk/haproxy:${CI_SHORT_TAG}-lts";
        docker push "joramk/haproxy:${CI_SHORT_TAG}-lts";;
      esac
    - docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" "joramk/haproxy:$CI_COMMIT_TAG"
    - docker push "joramk/haproxy:$CI_COMMIT_TAG"
    - case "$CI_COMMIT_TAG" in *\-*)
        CI_SHORT_TAG=`echo "$CI_COMMIT_TAG" | sed -e 's/\([0-9.]*\).*/\1/'`;
        docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" "$CI_REGISTRY_IMAGE:$CI_SHORT_TAG";
        docker push "$CI_REGISTRY_IMAGE:$CI_SHORT_TAG";;
      esac
    - case "$CI_COMMIT_TAG" in *\-*) CI_SHORT_TAG=`echo "$CI_COMMIT_TAG" | sed -e 's/\([0-9.]*\).*/\1/'`;
        docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" "joramk/haproxy:$CI_SHORT_TAG";
        docker push "joramk/haproxy:$CI_SHORT_TAG";;
      esac
  except:
    - master

after_script:
  - docker buildx stop haproxy_builder1
  - docker buildx rm haproxy_builder1
