#!/bin/bash
if [ -f /.env-haproxy-letsencrypt-renew ]; then
        certbot renew --reuse-key \
		--preferred-challenges http-01 \
		--rsa-key-size 4096 \
		--http-01-port=8888 \
		--post-hook="/usr/local/sbin/certbot-posthook" \
		"$@"
else
        exit 2
fi
