#!/bin/bash
#
# Creates a list of all LetsEncrypt certificates in /tmp/letsencrypt.list
#
# The list can be used to load all certificates via crt-file in haproxy.cfg
# Please be advised that OCSP stapling can't be used when certificates are
# included via crt-file directive and not as single file via crt directive.
#
LE_PATH=/etc/letsencrypt/live
LE_LIST=/tmp/letsencrypt.list
LE_CERT=fullkeychain.pem

rm -f $LE_LIST
touch $LE_LIST

if [ -e "$LE_PATH/*/$LE_CERT" ]; then
	certs=`ls $LE_PATH/*/$LE_CERT | sort`
	for cert in $certs; do
		echo $cert >>$LE_LIST
	done
fi
