#!/bin/bash

if [ "$1" != "--no-reload" ]; then
	POSTHOOK="/usr/local/sbin/certbot-posthook"
else
	POSTHOOK="/usr/local/sbin/certbot-posthook --no-reload"
	shift 1
fi

if [ -f /.env-haproxy-letsencrypt-renew ]; then
        certbot renew --reuse-key \
		--preferred-challenges http-01 \
		--rsa-key-size 4096 \
		--http-01-port=8888 \
		--deploy-hook="$POSTHOOK" \
		"$@"
fi
