#!/bin/bash

#
# Create HAProxy compatible chained certificate files
# with private key attached.
#

for dir in $(ls -d /etc/letsencrypt/live/*); do
        cat $dir/privkey.pem $dir/fullchain.pem > /etc/haproxy/letsencrypt/`basename $dir`.pem
done

kill -HUP 1
