#!/bin/bash
if [ -f /.env-haproxy-letsencrypt ] && [ -f /.env-haproxy-letsencrypt-ocsp ]; then
	LE_PATH=/etc/letsencrypt/live
	for OCSP_DOMAIN in $LE_PATH/*; do
	 OCSP_URL=$(openssl x509 -noout -ocsp_uri -in /etc/haproxy/letsencrypt/`basename ${OCSP_DOMAIN}`.pem)
	 openssl ocsp -no_nonce -respout /etc/haproxy/letsencrypt/`basename ${OCSP_DOMAIN}`.pem.ocsp \
	  -issuer ${OCSP_DOMAIN}/chain.pem \
	  -verify_other ${OCSP_DOMAIN}/chain.pem \
	  -cert ${OCSP_DOMAIN}/cert.pem \
	  -url ${OCSP_URL} 2>/dev/null
	 if [ "$1" != "--fetch-only" ]; then
	  echo "set ssl ocsp-response $(base64 -w0 /etc/haproxy/letsencrypt/`basename ${OCSP_DOMAIN}`.pem.ocsp)" | /usr/bin/socat stdio /var/run/haproxy.admin
	 fi
	done
fi
