#!/bin/bash
if [ ! -f /.env-haproxy-letsencrypt ] || [ ! -f /.env-haproxy-letsencrypt-ocsp ]; then
	exit 2
fi

LE_PATH=/etc/letsencrypt/live

for OCSP_DOMAIN in $LE_PATH/*; do
 openssl ocsp -no_nonce -respout /etc/haproxy/letsencrypt/`basename ${OCSP_DOMAIN}`.ocsp \
  -issuer ${OCSP_DOMAIN}/chain.pem \
  -verify_other ${OCSP_DOMAIN}/chain.pem \
  -cert ${OCSP_DOMAIN}/cert.pem \
  -url http://ocsp.int-x3.letsencrypt.org/4 \
  -header "HOST=ocsp.int-x3.letsencrypt.org" 2>/dev/null
 echo "set ssl ocsp-response $(base64 -w0 /etc/haproxy/letsencrypt/`basename ${OCSP_DOMAIN}`.ocsp)" | /usr/bin/socat stdio /var/run/haproxy.admin
done

exit 0

